### PR TITLE
Added Article Page and some text/CSS edits to make it more obvious 

### PR DESCRIPTION
**Pull request by choudhs2**
Made ArticleList a full page component, added text and CSS to explain it neatly. Also immediately calls API when that page is loaded.

### CODE REVIEW

**Comment by alexlehuynh** [comment]
Looks good!

**Comment by hasnain-commits** [comment]
Seems good

**Comment by wy33** [comment]
Looks good

**Comment by wy33** [comment]
Rebased in local vscode editor and pushed to resolve conflicts, merging now

**Pull request merged**
